### ISSUE TITLE
Add project logo

### ISSUE THREAD

**Issue by manosbatsis** [manosbatsis/partiture#3]
- Final logo must be in vector format
- Must have even width/height dimensions 
- Must render well as an .ico

Ideas welcome.

**Comment by mirzazulfan** [comment]
Hi @manosbatsis what about this?
![partiture](https://user-images.githubusercontent.com/36124339/53557235-140cac80-3b78-11e9-9f7b-cf02d7205fb1.png)

**Comment by manosbatsis** [comment]
Hey @mirzazulfan, thank you for your submission - this looks great! Can you submit a vector version?

**Comment by mirzazulfan** [comment]
hI @manosbatsis Thanks for your response, im glad you liked it. You can download all files [here](https://drive.google.com/drive/folders/1qwvh-h77uYUqJAYwaqMsqFdv7XccNT9p).  If you need anything change please let me know. Best regard!

**Comment by manosbatsis** [comment]
you rock @mirzazulfan ! i'll update this when the logo is applied.

**Comment by manosbatsis** [comment]
Applied and updated changelog, thanks again @mirzazulfan !
